services:
  sparkframe-firestarter:
    image: sparkframe-firestarter:latest
    container_name: sparkframe-firestarter-app
    build:
      context: .
      secrets: [composer_auth]
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      
secrets:
  composer_auth:
    file: ${COMPOSER_AUTH_PATH}