services:
  sparkframe-firestarter:
    image: sparkframe-firestarter:dev
    container_name: sparkframe-firestarter-app-dev
    build:
      target: dev
    environment:
      XDEBUG_MODE: debug,develop
      XDEBUG_CONFIG: client_port=${XDEBUG_HOST_PORT} start_with_request=yes idekey=VSCODE
