services:
  db:
    image: mysql:9.5.0
    container_name: mysql-db-notes
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: notes_app
    ports:
      - 3306:3306
    volumes:
      - mysql-db-notes-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 10s

volumes:
  mysql-db-notes-volume: