services:
  sparkframe-firestarter-dev:
    image: sparkframe-firestarter:dev
    container_name: sparkframe-firestarter-app-dev
    build:
      context: .
      secrets: [composer_auth]
      target: dev
    ports:
      - 8000:80
    volumes:
      - ./public:/var/www/html/public
      - ./sqlite_db:/var/www/html/sqlite_db
      - ./src:/var/www/html/src
      - ./.env:/var/www/html/.env
      - ./composer.json:/var/www/html/composer.json
      - ./.gitignore:/var/www/html/.gitignore
    environment:
      XDEBUG_MODE: debug,develop
      XDEBUG_CONFIG: client_port=${XDEBUG_HOST_PORT} start_with_request=yes idekey=VSCODE

secrets:
  composer_auth:
    file: ${COMPOSER_AUTH_PATH}