services:
  sparkframe-firestarter-dev:
    image: sparkframe-firestarter:dev
    container_name: sparkframe-firestarter-app-dev
    build:
      context: .
      secrets: [composer_auth]
      target: dev
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - vendor_dev:/var/www/html/vendor
    environment:
      XDEBUG_MODE: debug,develop
      XDEBUG_CONFIG: client_port=${XDEBUG_HOST_PORT} start_with_request=yes idekey=VSCODE
  db:
    image: mysql:9.5.0
    container_name: mysql-db-notes
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: notes-app
    ports:
      - 3306:3306
    volumes:
      - mysql-db-notes-volume:/var/lib/mysql

secrets:
  composer_auth:
    file: ${COMPOSER_AUTH_PATH}

volumes:
  vendor_dev:
  mysql-db-notes-volume: