# In case you have private composer packages you want to install in this project
# you can uncomment the commented out secret sections.
services:
  sparkframe-firestarter:
    image: sparkframe-firestarter:production
    container_name: sparkframe-firestarter-app-production
    build:
      context: .
      # secrets: [composer_auth] # Uncomment if you are using private composer packages
      target: production
    ports:
      - 8001:80
    volumes:
      - .:/var/www/html
      - vendor_prod:/var/www/html/vendor
    depends_on:
      db:
        condition: service_healthy

# Uncomment if you are using private composer packages
# secrets:
#   composer_auth:
#     file: ${COMPOSER_AUTH_PATH}

volumes:
  vendor_prod: